INSERT INTO GENRE VALUES('Action');
INSERT INTO GENRE VALUES('Comedy');
INSERT INTO GENRE VALUES('Romance');
INSERT INTO GENRE VALUES('Thiller');
INSERT INTO GENRE VALUES('Adventure');
--SF
INSERT INTO GENRE VALUES('Sci-Fi');
INSERT INTO GENRE VALUES('Fantasy');